<a href="https://colab.research.google.com/github/MatheusrCunha/py_class/blob/main/Modelagem-Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install control

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 455.1/455.1 kB 5.8 MB/s eta 0:00:00


In [21]:
import control as clt
import numpy as np
import scipy.signal as sg
import numpy as np

v = [1, 2, 3, 4, 5]
print(v)
n = [5, 3]
d = [1, 6, 11, 6]
G1 = clt.tf(n, d)
print(G1)

rn = np.roots(n)
rd = np.roots(d)

print(rn)
print(rd)

r, p, k = sg.residue(n, d)
print(r)

#reshape vetor em python

[1, 2, 3, 4, 5]

       5 s + 3
----------------------
s^3 + 6 s^2 + 11 s + 6

[-0.6]
[-3. -2. -1.]
[-1.  7. -6.]


In [35]:
import numpy as np
lista = list(range(-10, 13, 2))
print(lista)

lista = list(range(-10, 13, 2))
#lista_coluna = np.arange(1, 10, -1.5)
z = np.arange(1, -10, -1.5)
lista_coluna = z.reshape(-1, 1)
print(lista_coluna)

element_1 = lista_coluna[2] ** 2
element_2 = lista_coluna[5] ** 2
print(element_1)
print(element_2)

array = np.random.randint(10, size=(2, 5))
print(array)

n = [1, 4]
d = [1, 1, 1, -1, 1, 2]
G1 = clt.tf(n, d)
print(G1)

[-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 12]
[[ 1. ]
 [-0.5]
 [-2. ]
 [-3.5]
 [-5. ]
 [-6.5]
 [-8. ]
 [-9.5]]
[4.]
[42.25]
[[3 4 7 7 8]
 [9 5 7 9 4]]

            s + 4
-----------------------------
s^5 + s^4 + s^3 - s^2 + s + 2

