<a href="https://colab.research.google.com/github/MatheusrCunha/py_class/blob/main/Modelagem-Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
pip install control

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 455.1/455.1 kB 6.3 MB/s eta 0:00:00


In [ ]:
import control as clt
import numpy as np
import scipy.signal as sg
import numpy as np

v = [1, 2, 3, 4, 5]
print(v)
n = [5, 3]
d = [1, 6, 11, 6]
G1 = clt.tf(n, d)
print(G1)

rn = np.roots(n)
rd = np.roots(d)

print(rn)
print(rd)

r, p, k = sg.residue(n, d)
print(r)

#reshape vetor em python

[1, 2, 3, 4, 5]

       5 s + 3
----------------------
s^3 + 6 s^2 + 11 s + 6

[-0.6]
[-3. -2. -1.]
[-1.  7. -6.]


In [7]:
import control as clt
import numpy as np
lista = list(range(-10, 13, 2))
print(lista)

lista = list(range(-10, 13, 2))
#lista_coluna = np.arange(1, 10, -1.5)
z = np.arange(1, -10, -1.5)
lista_coluna = z.reshape(-1, 1)
print(lista_coluna)

element_1 = lista_coluna[2] ** 2
element_2 = lista_coluna[5] ** 2
print(element_1)
print(element_2)

array = np.random.randint(10, size=(2, 5))
print(array)

columns = [2, 3, 4]
extracted_array = array[:, columns]

print(extracted_array)

matrix = np.zeros((3, 3))
print(matrix)

n = [1, 4]
d = [0, -1, -1, -1, -2]
G1 = clt.tf(n, d)
print(G1)

n = [3]
d = [0, ]
G1 = clt.tf(n, d)
print(G1)



[-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 12]
[[ 1. ]
 [-0.5]
 [-2. ]
 [-3.5]
 [-5. ]
 [-6.5]
 [-8. ]
 [-9.5]]
[4.]
[42.25]
[[4 0 4 8 8]
 [9 0 3 8 2]]
[[4 8 8]
 [3 8 2]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

      s + 4
------------------
-s^3 - s^2 - s - 2



In [10]:
try:
    import control as ctl
except:
    %pip install control
import control as ctl
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

Num = input('Digite o numerador da funcao transferencia: ') #Entre com o numerador da ft, ex: (1 3) = (s + 3)
Den = input('Digite o denominador da funcao transferencia: ') #Entre com o denominador da ft, ex: (1 2) = (s + 2)

Ns = Num.split() #Retorna uma lista de string, quebra no espaço
Ds = Den.split() #Retorna uma lista de string, quebra no espaço

print('Numerador: ', Ns) #print o numerador
print('Denominador: ', Ds) #print o denominador

Numvet = list(map(float, Ns)) #Converte para float
DenVet = list(map(float, Ds)) #Converte para float

sys = ctl.tf(Numvet, DenVet) #cria a função de transferência
print(sys) #Mostra a função de tranferência

KeyboardInterrupt: ignored